# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCSn15lmPcd_EIxie0fsXACrpG5Oemqy
"""

import requests
import time

# --- CONFIGURACIÓN ---
TOKEN = "8107696402:AAEwS9w1AcFYY8jY-vrENEtcvkEcAjuq-QI"
CHAT_ID = "@AgroDMGRbot"

# Coordenadas geográficas aproximadas que cubren México
MEXICO_BOUNDS = {
    "lat_min": 14.5, "lat_max": 32.7,
    "lon_min": -118.4, "lon_max": -86.7
}

def obtener_sismos_usgs():
    url = "https://earthquake.usgs.gov/earthquakes/feed/v1.0/summary/all_hour.geojson"
    try:
        response = requests.get(url, timeout=10)
        data = response.json()
        sismos_en_mexico = []

        for feature in data['features']:
            coords = feature['geometry']['coordinates'] # [lon, lat, profundidad]
            lon, lat = coords[0], coords[1]

            # Verificación: ¿Está en México?
            if (MEXICO_BOUNDS["lat_min"] <= lat <= MEXICO_BOUNDS["lat_max"] and
                MEXICO_BOUNDS["lon_min"] <= lon <= MEXICO_BOUNDS["lon_max"]):
                sismos_en_mexico.append(feature)

        return sismos_en_mexico
    except Exception as e:
        print(f"Error conectando a USGS: {e}")
        return []

def enviar_telegram(sismo):
    prop = sismo['properties']
    msg = (f"⚠️ **SISMO DETECTADO (USGS)**\n\n"
           f"📍 **Lugar:** {prop['place']}\n"
           f"📈 **Magnitud:** {prop['mag']}\n"
           f"🕒 **Hora:** {time.ctime(prop['time']/1000)}\n"
           f"🔗 [Ver en USGS]({prop['url']})")

    url = f"https://api.telegram.org/bot{TOKEN}/sendMessage"
    requests.post(url, data={"chat_id": CHAT_ID, "text": msg, "parse_mode": "Markdown"})

# --- BUCLE PRINCIPAL ---
vistos = set()
print("Monitoreando sismos en México vía USGS...")

while True:
    sismos = obtener_sismos_usgs()
    for s in sismos:
        s_id = s['id']
        if s_id not in vistos:
            # Solo avisar si la magnitud es relevante (ej. > 4.0)
            if s['properties']['mag'] >= 4.0:
                enviar_telegram(s)
            vistos.add(s_id)

    time.sleep(60) # Espera 1 minuto antes de volver a consultar